### PR TITLE
Add tiling, and refactor a bit

### LINKED ISSUE #3: Add raster extension

### PR DESCRIPTION
**Pull request by gadomski**
**Related Issue(s):**
- Closes #3 

**Description:**
Adds a tiling scheme, and refactors some of the STAC item creation.

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [x] Documentation has been updated to reflect changes, if applicable.
- [x] Examples have been updated to reflect changes, if applicable
- [ ] Changes are added to the [CHANGELOG](../CHANGELOG.md).

### CODE REVIEW

**Review by pholleway — APPROVED** [review]

**Review by pjhartzell — APPROVED** [review]
Looks sharp! Clean code. I like the tiler. Tests pass, nothing jumps out at me in the Collections and Items. 

Not deal breakers:
1. The function docs are a little light. But we're not publishing an API, so probably just fine.
2. Bouncing back a comment...use the grid extension? 🙂

**Comment by gadomski** [comment]
> The function docs are a little light. But we're not publishing an API, so probably just fine.

Yeah, agreed. I didn't doc in the interest of time. I've opened an issue to add docs, in case we ever are bored :-). #9 

>Bouncing back a comment...use the grid extension? 🙂

I'm not gridding to any predefined system, and in fact I'm allowing the grid size to be customizable -- I didn't really see the value add in putting the grid code into the items. The bounding box / geometry defines the grid?

**Comment by pjhartzell** [comment]
>I'm not gridding to any predefined system, and in fact I'm allowing the grid size to be customizable -- I didn't really see the value add in putting the grid code into the items. 

I think you're right. I usually add a custom field to Item properties when I have a grid, even if it is custom, just to allow filtering for a specific tile. But that may be overkill. Since you don't need to use a predefined system to use the grid extension, I've been wondering if using the grid extension is an appropriate replacement for these custom fields that describe custom grids. But perhaps only using the grid extension for well-known grids is best.

**Comment by gadomski** [comment]
> But perhaps only using the grid extension for well-known grids is best.

I think the grid extension makes sense for well-known (MGRS) or fixed (one degree boxes for global datasets) grids.

**Pull request merged**
